theme: jekyll-theme-slate
title: A Comparison of Number Representations for Hardware Multiply-and-Accumulate Units
description: A project as part of EE 241B at UC Berkeley by Kat Li Yang and Jingyi Xu
